//resource.h
#pragma once

enum {

    //null resource - test
    IDR_NULL = 0x0000,

    //fonts
    IDR_FNT_SMALL,
    IDR_FNT_NORMAL,
    IDR_FNT_BIG,
    IDR_FNT_TERMINAL,
    IDR_FNT_SPECIAL,

    //pngs
    IDR_PNG_marlin_logo,
    IDR_PNG_prusa_printer_splash,
    IDR_PNG_prusa_printer_logo,

    IDR_PNG_nozzle_16px,
    IDR_PNG_heatbed_16px,
    IDR_PNG_speed_16px,
    IDR_PNG_spool_16px,
    IDR_PNG_z_axis_16px,
    IDR_PNG_home_shape_16px,
    IDR_PNG_print_16px,
    IDR_PNG_x_axis_16x16,
    IDR_PNG_y_axis_16x16,
    IDR_PNG_z_axis_16x16,
    IDR_PNG_turbine_16x16,
    IDR_PNG_fan_16x16,
    IDR_PNG_selftest_16x16,
    IDR_PNG_wizard_16x16,
    IDR_PNG_filament_sensor_17x16,

    IDR_PNG_print_58px,
    IDR_PNG_preheat_58px,
    IDR_PNG_spool_58px,
    IDR_PNG_reprint_48px,
    IDR_PNG_calibrate_58px,
    IDR_PNG_settings_58px,
    IDR_PNG_info_58px,
    IDR_PNG_pause_58px,
    IDR_PNG_stop_58px,
    IDR_PNG_resume_48px,
    IDR_PNG_home_58px,
    IDR_PNG_info_48px,
    IDR_PNG_error_white_48px,
    IDR_PNG_warning_48px,
    IDR_PNG_question_48px,

    IDR_PNG_home_full_16px,
    IDR_PNG_folder_full_16px,
    IDR_PNG_folder_up_16px,
    IDR_PNG_folder_shape_16px,
    IDR_PNG_folder_open_16px,

    IDR_PNG_pepa_64px,
    IDR_PNG_wifi_large_64x64,

    IDR_PNG_dash_18px,
    IDR_PNG_ok_color_18px,
    IDR_PNG_nok_color_18px,
    IDR_PNG_spinner1_16px,
    IDR_PNG_spinner2_16px,
    IDR_PNG_spinner3_16px,
    IDR_PNG_spinner4_16px,
    IDR_PNG_hourglass_39px,
    IDR_PNG_wizard_icon_autohome,
    IDR_PNG_wizard_icon_search,
    IDR_PNG_wizard_icon_measure,
    IDR_PNG_hand_154x65,
    IDR_PNG_nozzle_34x32,

    IDR_PNG_pepa_140px,

    IDR_PNG_usb_16px,
    IDR_PNG_lan_16px,
    IDR_PNG_wifi_16px,
    IDR_PNG_info_16px,
    IDR_PNG_error_16px,
    IDR_PNG_warning_16px,
    IDR_PNG_question_16px,
    IDR_PNG_sheets_profile_16px,
    IDR_PNG_nozzle_shape_48px,

    IDR_PNG_arrow_up_16px,
    IDR_PNG_arrow_down_16px,
    IDR_PNG_arrow_left_16px,
    IDR_PNG_arrow_right_16px,
    IDR_PNG_arrow_up_8px,
    IDR_PNG_arrow_down_8px,
    IDR_PNG_arrow_up_orange_8px,
    IDR_PNG_arrow_down_orange_8px,

    IDR_PNG_back_32px,
    IDR_PNG_serial_printing,
    IDR_PNG_disconnect_48px,
    IDR_PNG_switch_off_36px,
    IDR_PNG_switch_on_36px,
    IDR_PNG_hand_qr,
    IDR_PNG_exposure_times_48px,
    IDR_PNG_usb_error,
    IDR_PNG_fan_error,
    IDR_PNG_turn_knob,

    IDR_PNG_flag_cs,
    IDR_PNG_flag_de,
    IDR_PNG_flag_en,
    IDR_PNG_flag_es,
    IDR_PNG_flag_fr,
    IDR_PNG_flag_it,
    IDR_PNG_flag_pl,
};
