// screen_menus.hpp
#pragma once
#include "ScreenFactory.hpp"

ScreenFactory::UniquePtr GetScreenMenuFwUpdate();
ScreenFactory::UniquePtr GetScreenMenuLanguages();
ScreenFactory::UniquePtr GetScreenMenuLanguagesNoRet();
ScreenFactory::UniquePtr GetScreenMenuEthernetSettings();
ScreenFactory::UniquePtr GetScreenMenuWifiSettings();
ScreenFactory::UniquePtr GetScreenMenuHwSetup();
ScreenFactory::UniquePtr GetScreenMenuSteelSheets();
ScreenFactory::UniquePtr GetScreenEeprom();
ScreenFactory::UniquePtr GetScreenMenuFooterSettings();
ScreenFactory::UniquePtr GetScreenMenuFooterSettingsAdv();
ScreenFactory::UniquePtr GetScreenPrusaLink();
ScreenFactory::UniquePtr GetScreenMenuConnect();
ScreenFactory::UniquePtr GetScreenMenuExperimentalSettings();
ScreenFactory::UniquePtr GetScreenMenuEepromDiagnostics();
ScreenFactory::UniquePtr GetScreenMenuNetwork();
ScreenFactory::UniquePtr GetScreenMenuTest();
