#include <option/mdns.h>

LWIP_MALLOC_MEMPOOL_START
#if MDNS()
LWIP_MALLOC_MEMPOOL(7, 128)
#else
LWIP_MALLOC_MEMPOOL(6, 128)
#endif
LWIP_MALLOC_MEMPOOL(2, 512)
LWIP_MALLOC_MEMPOOL(1, 1512)
LWIP_MALLOC_MEMPOOL_END
