//----------------------------------------------------------------------------//
// pin names
#pragma once

#include "Pin.hpp"

#define MARLIN_PORT_PIN_HW_IDENTIFY    MARLIN_PORT_PIN(MARLIN_PORT_A, MARLIN_PIN_3) //ADC, unused
#define MARLIN_PORT_PIN_TEMP_BED       MARLIN_PORT_PIN(MARLIN_PORT_A, MARLIN_PIN_4) //ADC
#define MARLIN_PORT_PIN_THERM2         MARLIN_PORT_PIN(MARLIN_PORT_A, MARLIN_PIN_5) //ADC
#define MARLIN_PORT_PIN_TEMP_HEATBREAK MARLIN_PORT_PIN(MARLIN_PORT_A, MARLIN_PIN_6) //ADC
#define MARLIN_PORT_PIN_TEMP_0         MARLIN_PORT_PIN(MARLIN_PORT_C, MARLIN_PIN_0) //ADC

#define MARLIN_PORT_Z_MIN     MARLIN_PORT_A
#define MARLIN_PIN_Z_MIN      MARLIN_PIN_8
#define MARLIN_PORT_PIN_Z_MIN MARLIN_PORT_PIN(MARLIN_PORT_Z_MIN, MARLIN_PIN_Z_MIN)
extern InputPin zMin;

#define MARLIN_PORT_X_DIAG     MARLIN_PORT_E
#define MARLIN_PIN_X_DIAG      MARLIN_PIN_2
#define MARLIN_PORT_PIN_X_DIAG MARLIN_PORT_PIN(MARLIN_PORT_X_DIAG, MARLIN_PIN_X_DIAG)
extern InputPin xDiag;

#define MARLIN_PORT_Y_DIAG     MARLIN_PORT_E
#define MARLIN_PIN_Y_DIAG      MARLIN_PIN_1
#define MARLIN_PORT_PIN_Y_DIAG MARLIN_PORT_PIN(MARLIN_PORT_Y_DIAG, MARLIN_PIN_Y_DIAG)
extern InputPin yDiag;

#define MARLIN_PORT_Z_DIAG     MARLIN_PORT_E
#define MARLIN_PIN_Z_DIAG      MARLIN_PIN_3
#define MARLIN_PORT_PIN_Z_DIAG MARLIN_PORT_PIN(MARLIN_PORT_Z_DIAG, MARLIN_PIN_Z_DIAG)
extern InputPin zDiag;

#define MARLIN_PORT_E0_DIAG     MARLIN_PORT_A
#define MARLIN_PIN_E0_DIAG      MARLIN_PIN_15
#define MARLIN_PORT_PIN_E0_DIAG MARLIN_PORT_PIN(MARLIN_PORT_E0_DIAG, MARLIN_PIN_E0_DIAG)
extern InputPin e0Diag;

#define MARLIN_PORT_X_STEP     MARLIN_PORT_D
#define MARLIN_PIN_X_STEP      MARLIN_PIN_1
#define MARLIN_PORT_PIN_X_STEP MARLIN_PORT_PIN(MARLIN_PORT_X_STEP, MARLIN_PIN_X_STEP)
extern OutputPin xStep;

#define MARLIN_PORT_X_DIR     MARLIN_PORT_D
#define MARLIN_PIN_X_DIR      MARLIN_PIN_0
#define MARLIN_PORT_PIN_X_DIR MARLIN_PORT_PIN(MARLIN_PORT_X_DIR, MARLIN_PIN_X_DIR)
extern OutputPin xDir;

#define MARLIN_PORT_X_ENA     MARLIN_PORT_D
#define MARLIN_PIN_X_ENA      MARLIN_PIN_3
#define MARLIN_PORT_PIN_X_ENA MARLIN_PORT_PIN(MARLIN_PORT_X_ENA, MARLIN_PIN_X_ENA)
extern OutputPin xEnable;

#define MARLIN_PORT_Y_STEP     MARLIN_PORT_D
#define MARLIN_PIN_Y_STEP      MARLIN_PIN_13
#define MARLIN_PORT_PIN_Y_STEP MARLIN_PORT_PIN(MARLIN_PORT_Y_STEP, MARLIN_PIN_Y_STEP)
extern OutputPin yStep;

#define MARLIN_PORT_Y_DIR     MARLIN_PORT_D
#define MARLIN_PIN_Y_DIR      MARLIN_PIN_12
#define MARLIN_PORT_PIN_Y_DIR MARLIN_PORT_PIN(MARLIN_PORT_Y_DIR, MARLIN_PIN_Y_DIR)
extern OutputPin yDir;

#define MARLIN_PORT_Y_ENA     MARLIN_PORT_D
#define MARLIN_PIN_Y_ENA      MARLIN_PIN_14
#define MARLIN_PORT_PIN_Y_ENA MARLIN_PORT_PIN(MARLIN_PORT_Y_ENA, MARLIN_PIN_Y_ENA)
extern OutputPin yEnable;

#define MARLIN_PORT_Z_STEP     MARLIN_PORT_D
#define MARLIN_PIN_Z_STEP      MARLIN_PIN_4
#define MARLIN_PORT_PIN_Z_STEP MARLIN_PORT_PIN(MARLIN_PORT_Z_STEP, MARLIN_PIN_Z_STEP)
extern OutputPin zStep;

#define MARLIN_PORT_Z_DIR     MARLIN_PORT_D
#define MARLIN_PIN_Z_DIR      MARLIN_PIN_15
#define MARLIN_PORT_PIN_Z_DIR MARLIN_PORT_PIN(MARLIN_PORT_Z_DIR, MARLIN_PIN_Z_DIR)
extern OutputPin zDir;

#define MARLIN_PORT_Z_ENA     MARLIN_PORT_D
#define MARLIN_PIN_Z_ENA      MARLIN_PIN_2
#define MARLIN_PORT_PIN_Z_ENA MARLIN_PORT_PIN(MARLIN_PORT_Z_ENA, MARLIN_PIN_Z_ENA)
extern OutputPin zEnable;

#define MARLIN_PORT_E0_STEP     MARLIN_PORT_D
#define MARLIN_PIN_E0_STEP      MARLIN_PIN_9
#define MARLIN_PORT_PIN_E0_STEP MARLIN_PORT_PIN(MARLIN_PORT_E0_STEP, MARLIN_PIN_E0_STEP)
extern OutputPin e0Step;

#define MARLIN_PORT_E0_DIR     MARLIN_PORT_B
#define MARLIN_PIN_E0_DIR      MARLIN_PIN_8
#define MARLIN_PORT_PIN_E0_DIR MARLIN_PORT_PIN(MARLIN_PORT_E0_DIR, MARLIN_PIN_E0_DIR)
extern OutputPin e0Dir;

#define MARLIN_PORT_E0_ENA     MARLIN_PORT_D
#define MARLIN_PIN_E0_ENA      MARLIN_PIN_10
#define MARLIN_PORT_PIN_E0_ENA MARLIN_PORT_PIN(MARLIN_PORT_E0_ENA, MARLIN_PIN_E0_ENA)
extern OutputPin e0Enable;

#define MARLIN_PORT_BED_HEAT     MARLIN_PORT_B
#define MARLIN_PIN_BED_HEAT      MARLIN_PIN_0
#define MARLIN_PORT_PIN_BED_HEAT MARLIN_PORT_PIN(MARLIN_PORT_BED_HEAT, MARLIN_PIN_BED_HEAT)
extern OutputPin bedHeat;

#define MARLIN_PORT_HEAT0     MARLIN_PORT_B
#define MARLIN_PIN_HEAT0      MARLIN_PIN_1
#define MARLIN_PORT_PIN_HEAT0 MARLIN_PORT_PIN(MARLIN_PORT_HEAT0, MARLIN_PIN_HEAT0)
extern OutputPin heat0;

#define MARLIN_PORT_FAN     MARLIN_PORT_E
#define MARLIN_PIN_FAN      MARLIN_PIN_11
#define MARLIN_PORT_PIN_FAN MARLIN_PORT_PIN(MARLIN_PORT_FAN, MARLIN_PIN_FAN)
extern OutputPin fan;

#define MARLIN_PORT_FAN1     MARLIN_PORT_E
#define MARLIN_PIN_FAN1      MARLIN_PIN_9
#define MARLIN_PORT_PIN_FAN1 MARLIN_PORT_PIN(MARLIN_PORT_FAN1, MARLIN_PIN_FAN1)
extern OutputPin fan;

#define PIN_FSENSOR TPB4
