#pragma once

#ifdef __cplusplus
extern "C" {
#endif //__cplusplus

void MINDA_BROKEN_CABLE_DETECTION__BEGIN();
void MINDA_BROKEN_CABLE_DETECTION__PRE_XYHOME();
void MINDA_BROKEN_CABLE_DETECTION__POST_XYHOME();
void MINDA_BROKEN_CABLE_DETECTION__POST_ZHOME_0();
void MINDA_BROKEN_CABLE_DETECTION__POST_ZHOME_1();
void MINDA_BROKEN_CABLE_DETECTION__END();

void MINDA_BROKEN_CABLE_DETECTION__MBL_BEGIN();
void MINDA_BROKEN_CABLE_DETECTION__PRE_XYMOVE();
void MINDA_BROKEN_CABLE_DETECTION__POST_XYMOVE();
void MINDA_BROKEN_CABLE_DETECTION__MBL_END();

#ifdef __cplusplus
}
#endif //__cplusplus
