name: Mark stale issues

on:
  schedule:
  # 1:30 AM on MON/TUE/WED/THU
  - cron: "30 1 * * 1,2,3,4"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Don't ever mark PRs as stale.
        days-before-pr-stale: -1
        stale-issue-message: 'Thank you for your contribution to our project. This issue has not received any updates for 60 days and may be considered "stale." If this issue is still important to you, please add an update within the next 7 days to keep it open. Administrators can manually reopen the issue if necessary.'
        close-issue-message: 'This issue has been closed due to lack of recent activity. Please consider opening a new one if needed.'
        # Don't act on things assigned to a milestone or assigned to someone.
        exempt-all-milestones: true
        exempt-all-assignees: true
        enable-statistics: true
        # Disable this and change the operations per run back to 30 when this goes live.
        debug-only: false
        operations-per-run: 200
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
        ascending: true
